name: ratelimit
description: Kentik envoy rate limiter fork
version: TAG
target:
  build: unset GOPATH && make -f Makefile.kentik all install
  test: kbt go-mod-tests
lint:
  golinter: golangci-lint
  go:
    - errcheck:error
