name: api-ratelimit
description: Kentik envoy rate limiter fork
version: TAG
target:
  build: unset GOPATH && make -f Makefile.kentik all install
  test: kbt go-mod-tests
lint:
  go:
    - errcheck:error
nomad:
  - service_group: apigw-ratelimit
    pack: service
    branch: hiera
