---
# pre-auth rate limiter to deal with ddos
domain: ddos
descriptors:
  - key: remote_address
    rate_limit:
      requests_per_unit: 1000
      unit: second

  # black listing an IP
  - key: remote_address
    value: 8.8.8.8
    rate_limit:
      unit: second
      requests_per_unit: 0
